### PR TITLE
Modify whitespace in cleaner/scheduled_tasks install.xml file #101

### LINKED ISSUE #101: Unit test failure in totara: XMLDB file is different to the generated version cleaner/scheduled_tasks
> root@58356ed20e6a:/siteroot# vendor/bin/phpunit tool_xmldb_instal_xml_testcase admin/tool/xmldb/tests/install_xml_test.php 
> Totara 10.19 (Build: 20190322.00), c8c87eb944c29f528ce20960570e2117ae9a8652
> PHP: 7.0.33.0.0.16.04.12, pgsql: 11.1 (Debian 11.1-1.pgdg90+1), OS: Linux 4.15.0-88-generic x86_64
> PHPUnit 5.7.27 by Sebastian Bergmann and contributors.
> 
> F                                                                   1 / 1 (100%)
> 
> Time: 1.25 seconds, Memory: 42.00MB
> 
> There was 1 failure:
> 
> 1) tool_xmldb_instal_xml_testcase::test_all_install_xml_files_formatted_correctly
> XMLDB file '/siteroot/local/datacleaner/cleaner/scheduled_tasks/db/install.xml' is different to the generated version, please edit the file in XMLDB editor and save it.
> Failed asserting that false is true.
> 
> /siteroot/admin/tool/xmldb/tests/install_xml_test.php:52
> /siteroot/lib/phpunit/classes/base_testcase.php:600
> /siteroot/lib/phpunit/classes/advanced_testcase.php:68
> 
> To re-run:
>  vendor/bin/phpunit tool_xmldb_instal_xml_testcase admin/tool/xmldb/tests/install_xml_test.php
> 
> FAILURES!
> Tests: 1, Assertions: 211, Failures: 1.
> 

Just needs a slight modification to the install.xml file, whitespace issues.

### PR DESCRIPTION
**Pull request by kristian-94**
This fixes #101

### CODE REVIEW

**Comment by danmarsden** [comment]
Do we really still need to be testing this against Moodle 2.6 - > 3.0 and with PHP 5 ? - this config generates 28 build tasks...

**Comment by kristian-94** [comment]
@danmarsden  which travis tests do you think are appropriate? We have said this plugin supports down to moodle 2.6

**Comment by danmarsden** [comment]
I would vote for moodle supported branches only. (3.5, 3.7, 3.8, master) But theres a case to drop in a couple of earlier branches for pseudo totara support.

**Comment by kristian-94** [comment]
@danmarsden  see how this looks to you now. I removed most of the old moodles but left 3.1 and a 2.9 branch in there.

**Comment by danmarsden** [comment]
thanks @kristian-94 - If it was my plugin I'd drop some of the Moodle 3.6 stuff (we're testing it 4 times on php 7.0, 7.2) and support for 3.6 ends in 2 months... but... it's not my plugin and this decreases the amount of noise in travis so +1 from me! :-)

**Pull request merged**
