### PR TITLE
Fix typo in language pack

### PR DESCRIPTION
**Pull request by abias**

### CODE REVIEW

**Comment by brendanheywood** [comment]
Cleaning plugins' is not a typo, eg 'cleaning products' or 'cleaning chemicals' is more natural to me, at least in Australian English. If this is a strong preference in UK / EU flavored English then maybe this is something best submitted to AMOS?

**Comment by abias** [comment]
Hi Brendan,

Thanks for your feedback. I have to admit that I thought "cleansing" is a typo, but after looking at the dictionary, I saw that this is a valid term and comes from the cleaning industry. I have also seen that you are using some analogies to the cleaning industry in the plugin's README. 

However, I think it's still misunderstandable for non-native speakers. Perhaps it might make sense to change the term "No data cleansing plugins found" to "No data cleaner plugins found.". This would match the wording of the rest of the plugin's settings pages.

Thanks,
Alex

**Comment by abias** [comment]
Hey @brendanheywood and @roperto ,

it's been a long time since I opened this tiny PR.

May I ask if you have any intention to merge it finally? Otherwise, I would close it myself as unmerged and would then also delete my fork of the plugin.

Cheers,
Alex

**Comment by brendanheywood** [comment]
thanks @abias :)

**Comment by abias** [comment]
Awesome. Thank you, Brendan!

**Pull request merged**
